# Generated by Django 5.1.5 on 2025-02-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
