# Generated by Django 5.1.5 on 2025-02-08 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner_alter_lesson_course"),
        ("users", "0003_alter_payments_payment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "course",
                    models.ForeignKey(
                        default="NULL",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_subscribe",
                        to="materials.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_subscribe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на курс",
                "verbose_name_plural": "Подписки на курсы",
            },
        ),
    ]
