version: '3.9'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: >
      bash -c "celery -A config  worker --loglevel=info --pool=eventlet"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    env_file:
      - .env
    command: >
      bash -c "celery -A config beat --loglevel=info"
    depends_on:
      - redis
      - db

networks:
  default:

volumes:
  postgres_data:
  static_volume: